apiVersion: v1
kind: Service
metadata:
  name: educacionit-app
spec:
  type: NodePort
  selector:
    app: educacionit-app
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080  # Accesible desde http://localhost:30080
